"""OpenTag agent prompts."""

from .research import (
    NO_RESEARCH_TOOL_ADDENDUM,
    RESEARCH_TOOL_ADDENDUM,
    RESEARCHER_SYSTEM_PROMPT,
)
from .system import SYSTEM_PROMPT, WORKFLOW_PROMPT
from .tools import TOOLS_PROMPT

BASE_SYSTEM_PROMPT = SYSTEM_PROMPT + TOOLS_PROMPT + WORKFLOW_PROMPT

__all__ = [
    "BASE_SYSTEM_PROMPT",
    "NO_RESEARCH_TOOL_ADDENDUM",
    "RESEARCH_TOOL_ADDENDUM",
    "RESEARCHER_SYSTEM_PROMPT",
]
